name: MGZF
description: A new Flutter project

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^8.0.0

flutter:
  assets:
    - assets/Gz.PNG
