name: your_project_name
description: A new Flutter project

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # سایر پکیج‌های مورد نیاز

flutter:
  assets:
    - assets/Gz.PNG
