name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
        name: Setup Flutter

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug -t lib/main.dart

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
        name: Upload APK
